name = "josephmyoung-back"
compatibility_date = "2025-02-04"
compatibility_flags = [ "nodejs_compat" ]

main = "src/index.ts"

[[d1_databases]]
binding = "josephmyoung_back"
database_name = "josephmyoung-back"
database_id = "198e4bff-08d6-4c63-bd34-6804d359f3cb"
migrations_dir = "drizzle/migrations"

# [vars]
# MY_VAR = "my-variable"

# Workers Logs
# Docs: https://developers.cloudflare.com/workers/observability/logs/workers-logs/
# Configuration: https://developers.cloudflare.com/workers/observability/logs/workers-logs/#enable-workers-logs
[observability]
enabled = true

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

[[r2_buckets]]
bucket_name = "josephmyoung-back-bucket"
binding = "R2"

# [ai]
# binding = "AI"
